[phases.setup]
# Ставим Node.js, Python и готовую библиотеку Pandas
nixPkgs = ["nodejs", "python3", "python3Packages.pandas"]

[phases.install]
# Устанавливаем только пакеты для Node.js
cmds = ["npm install"]

[start]
# Запускаем сервер
cmd = "node server/index.js"