[project]
type = "node"

[build]
# Устанавливаем зависимости для Node и для Python
command = "npm install && pip install -r requirements.txt"

[start]
# Команда должна в точности повторять путь из твоей структуры
command = "node server/index.js"